name: CAR - All Deployer Copy (Lyle)    # currently auto-deploy to dev cc is turned off
on:
  workflow_dispatch:
    inputs:
      service:
        type: choice
        description: 'Select the service that you like to deploy (eg: collector, datastore, refinery)'
        options:
        - collector
        - datastore
        - refinery
      tags:
        description: 'Enter the tag that you like to deploy (eg: refinery-v1.16.0)'
      environment:
        type: choice
        description: Select the environment where you like to deploy
        options:
        - dev
        - test
        - production


jobs:
  validate-tag:
    runs-on: ubuntu-latest 

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
          
    - name: validate tag
      run: git show-ref --verify refs/tags/${{ github.event.inputs.tags }}
      
      
    - name: remove whitespaces
      id: remove_whitespaces
      run: echo "::set-output name=TAG_NAME::$(sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//'<<<${{ github.event.inputs.tags }})"
      
    - name: Output coverage found
      run: echo "Coverage found ${{steps.remove_whitespaces.outputs.TAG_NAME}}"
      
    - name: Refinery Deploy test
      if: ${{ github.event.inputs.service == 'refinery' }}
      run: git push origin ${{steps.remove_whitespaces.outputs.TAG_NAME}}:${{ github.event.inputs.environment }}/${{ github.event.inputs.service }} --force
      
       
  deploy-tag:
    runs-on: ubuntu-latest
    needs: [ validate-tag ]
    
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        token: ${{ secrets.TEST_SECRET }}
        
    - name: pull and fetch
      run: |
        git pull origin main
        git fetch
        
        
    - name: adf-deploy
      if: ${{ github.event.inputs.service == 'collector' }}
      uses: ./.github/workflows/build-job.yml
      with:
        environment: ${{ github.event.inputs.environment }}
        branch_name: ${{ github.event.inputs.environment }}/${{ github.event.inputs.service }}
  
        
