name: CAR - All Deployer    # currently auto-deploy to dev cc is turned off
on:
  workflow_dispatch:
    inputs:
      service:
        type: choice
        description: 'Select the service that you like to deploy (eg: collector, datastore, refinery)'
        options:
        - collector
        - datastore
        - refinery
      tags:
        description: 'Enter the tag that you like to deploy (eg: refinery-v1.16.0)'
      environment:
        type: choice
        description: Select the environment where you like to deploy
        options:
        - dev
        - test
        - production


jobs:
  validate-tag:
    runs-on: ubuntu-latest 

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
          
    - name: validate tag
      run: git show-ref --verify refs/tags/${{ github.event.inputs.tags }}
       
  deploy-tag:
    runs-on: ubuntu-latest
    needs: [ validate-tag ]
    
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        token: ${{ secrets.TEST_SECRET }}
        
    - name: pull and fetch
      run: |
        git pull origin main
        git fetch
        
    - name: Deploy # clean out branch and deploy tag
      env:
        token: ${{ secrets.TEST_SECRET }}
      run: |
        git push origin ${{ github.event.inputs.tags }}:${{ github.event.inputs.environment }}/${{ github.event.inputs.service }} --force
        
