name: CAR - All Deployer    # currently auto-deploy to dev cc is turned off
on:
  workflow_dispatch:
    inputs:
      service:
        type: choice
        description: 'Select the service that you like to deploy (eg: collector, datastore, refinery)'
        options:
        - collector
        - datastore
        - refinery
      tags:
        description: 'Enter the tag that you like to deploy (eg: refinery-v1.16.0)'
      environment:
        type: choice
        description: Select the environment where you like to deploy
        options:
        - dev
        - test
        - production


jobs:
  validate-tag:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{steps.remove_whitespaces.outputs.TAG_NAME}}

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        
    - name: remove whitespaces
      id: remove_whitespaces
      run: echo "::set-output name=TAG_NAME::$(sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//'<<<${{ github.event.inputs.tags }})"          
  
    - name: print input tag
      run: echo "tag provided ${{steps.remove_whitespaces.outputs.TAG_NAME}}"
  
    - name: validate tag # validate if tag belongs to that service and also checks if that tag exist in github
      if: ${{ startsWith(${{needs.validate-tag.outputs.tag}}, ${{ github.event.inputs.service }}) }}
      run: git show-ref --verify refs/tags/${{steps.remove_whitespaces.outputs.TAG_NAME}}
  
#     - name: validate tag exist
#       run: git show-ref --verify refs/tags/${{steps.remove_whitespaces.outputs.TAG_NAME}}
    
       
  deploy-tag:
    runs-on: ubuntu-latest
    needs: [ validate-tag ]
    
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        token: ${{ secrets.TEST_SECRET }}
        
    - name: pull and fetch
      run: |
        git pull origin main
        git fetch
        
    - name: Deploy test
      run: git push origin ${{needs.validate-tag.outputs.tag}}:${{ github.event.inputs.environment }}/${{ github.event.inputs.service }} --force
      
  adf-template-deploy:
    needs: [ deploy-tag ]
    if: ${{ github.event.inputs.service == 'collector' }}
    uses: ramandatascientist/test-repo/.github/workflows/build-job.yml@main
    with:
      environment: ${{ github.event.inputs.environment }}
      branch_name: ${{ github.event.inputs.environment }}/${{ github.event.inputs.service }}
      
#   deploy-adf:
#     runs-on: ubuntu-latest
#     needs: [ validate-tag ]
#     if: ${{ github.event.inputs.service == 'collector' }}
    
#     steps:
#     - uses: actions/checkout@v3
#       with:
#         ref: ${{ github.event.inputs.environment }}/${{ github.event.inputs.service }}
#         fetch-depth: 0
#         token: ${{ secrets.TEST_SECRET }}
        
#     - name: pull and fetch
#       uses: ramandatascientist/test-repo/.github/workflows/build-job.yml@main
#       with:
#         environment: ${{ github.event.inputs.environment }}
#         branch_name: ${{ github.event.inputs.environment }}/${{ github.event.inputs.service }}
        
        
