name: Collector - ADF - Build ARM Template
on:
  workflow_dispatch:
  push:
    branches:
      - 'main' # this will be main
      - 'release/[0-9]+' # this will be main
    paths:
      - '.github/workflows/collector-adf-arm-builder.yml' # this file
      - 'collector/adf/**'

env: # Common environment variables regardless of environment and region

  ADF_SOURCE_NAME: dev-use-collector-adf
  AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  EVENT_MESSAGE: ${{ github.event.head_commit.message }}

  # Source code of the ADF from which ARM template will be generated
  DATA_FACTORY_SOURCE_DIR: ${{ github.workspace }}/collector/adf

  # This directory is where package.json file is located for @microsoft/azure-data-factory-utilities package that is used to generate ARM templates
  BUILD_DIR: /collector/build/

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    environment: dev-use # Only run the build process in the dev environment. The built artifacts will be deployed using a different release / deploy workflow.

    env: # Environment variables specific to this job
      AZURE_RESOURCE_GROUP: dev-analytics-use

    # Checkout code -- this will check out the current branch (we need main) in which this workflow runs from
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:       # added this logic so it can auto-trigger semver CI job. https://github.com/EndBug/add-and-commit#the-commit-from-the-action-is-not-triggering-ci
        fetch-depth: 0
        token: ${{ secrets.AP_DEPLOY_SECRET }}

    # Show paths
    - name: Show Repo paths
      run: ls -R

    # Show the environment variables for debugging
    - name: Display Environment Variable
      uses: azure/powershell@v1
      with:
        inlineScript: |
          dir env:
        azPSVersion: '3.1.0'

    # Setup Node.js
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.5.0
      with:
       node-version: 14.x

    # Install Azure Data Factory utilities package
    - name: Install npm
      run: |
        npm --prefix .${{ env.BUILD_DIR }} install

    # Run Validate ADF
    - name: Validate ADF
      run: |
        npm --prefix .${{ env.BUILD_DIR }} run build validate ${{ env.DATA_FACTORY_SOURCE_DIR }} /subscriptions/${{ env.AZURE_SUBSCRIPTION_ID }}/resourceGroups/${{ env.AZURE_RESOURCE_GROUP }}/providers/Microsoft.DataFactory/factories/${{ env.ADF_SOURCE_NAME }}

    # Generate ARM Template
    - name: Generate ARM template
      run: |
        npm --prefix .${{ env.BUILD_DIR }} run build export ${{ env.DATA_FACTORY_SOURCE_DIR }} /subscriptions/${{ env.AZURE_SUBSCRIPTION_ID }}/resourceGroups/${{ env.AZURE_RESOURCE_GROUP }}/providers/Microsoft.DataFactory/factories/${{ env.ADF_SOURCE_NAME }} "${{ env.ADF_SOURCE_NAME }}"

    # Add and commit generated Arm Template files
    - name: Add and Commit
      uses: EndBug/add-and-commit@v7.5.0
      with:
        add: '.${{ env.BUILD_DIR }}${{ env.ADF_SOURCE_NAME }}/*.json --force' # only add json files, that are actual ARM template files. There are also ps1 scripts generated by the ARM template package. 
        author_name: 'Collector build workflow'
        message: 'Collector build workflow  automated message for release ${{ env.EVENT_MESSAGE }}'
