name: semver tag copy
on:
  push:
    branches:
      - 'main'
      - 'release/**'
    paths:
      - collector/**
      - refinery/**
      - datastore/**
      

env:
  PROJECT_DIR: ${{ github.event.inputs.paths }}
  PROJECT_NAME: ${{ matrix.service }}
  PROJECT_TAG_PREFIX: "${{ env.SERVICE_NAME }}-v"

concurrency:
  group: ${{ matrix.service }}-${{ github.ref }}  # !!! Need to verify this
  cancel-in-progress: true
  
  
jobs:
  calculate-version:
    name: Calculate Version
    runs-on: ubuntu-latest
    
    outputs:
      tag: ${{ steps.version.outputs.tag }}
      semVer: ${{ steps.version.outputs.semVer }}
      
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        
    - name: Determine Version
      id: version
      env:
        GIT_BRANCH: ${{ github.head_ref || github.ref_name }}
        GIT_TAG_PREFIX: ${{ env.PROJECT_TAG_PREFIX }}
      shell: bash
      run: ./bin/version.sh
      
    - name: Dump version metadata
      env:
        JSON: ${{ toJson(steps.version.outputs) }}
      run: |
        echo "$JSON" > version.json
        
    - name: Upload version metadata
      uses: actions/upload-artifact@v2
      with:
        name: metadata
        path: version.json

  tag-sources:
    name: 'Tag sources'
    runs-on: ubuntu-latest
    needs: [ calculate-version ]
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/release/') 
    env:
      TAG: ${{ needs.calculate-version.outputs.tag }}

    steps:
      - name: Create tag
        uses: actions/github-script@v6
        with:
          script: |
            await github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "refs/tags/${{ env.TAG }}",
              sha: context.sha
            })
